# version is now using "compose spec"
# v2 and v3 are now combined!
# docker-compose v1.27+ required
version: '3'

services:
  vote:
    image: gcr.io/tech-challange-305619/kpmg-challange-vote
    depends_on:
      redis:
        condition: service_healthy 
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  result:
    image: gcr.io/tech-challange-305619/kpmg-challange-result
    depends_on:
      db:
        condition: service_healthy 
    ports:
      - "5001:80"
    networks:
      - front-tier
      - back-tier

  worker:
    image: gcr.io/tech-challange-305619/kpmg-challange-worker
    depends_on:
      redis:
        condition: service_healthy 
      db:
        condition: service_healthy 
    networks:
      - back-tier

  redis:
    image: gcr.io/tech-challange-305619/kpmg-challange-redis
    volumes:
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/redis.sh
      interval: "5s"
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: gcr.io/tech-challange-305619/kpmg-challange-postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "5s"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
